"""empty message

Revision ID: 15658559b591
Revises: 5133a6bcd4f6
Create Date: 2022-06-18 02:23:14.788236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15658559b591'
down_revision = '5133a6bcd4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickets', sa.Integer(), nullable=True))

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'aircraft', ['plane'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('tickets')

    # ### end Alembic commands ###
