"""empty message

Revision ID: 5133a6bcd4f6
Revises: 6a34465c0bd0
Create Date: 2022-06-18 02:21:07.966885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5133a6bcd4f6'
down_revision = '6a34465c0bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickets', sa.Integer(), nullable=False))

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'aircraft', ['plane'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('tickets')

    # ### end Alembic commands ###
