"""empty message

Revision ID: 75c77be7631e
Revises: 
Create Date: 2022-06-15 23:08:33.587908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c77be7631e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure', sa.Column('depart_date', sa.DateTime(), nullable=False))
    op.add_column('departure', sa.Column('stopover_date', sa.DateTime(), nullable=True))
    op.add_column('departure', sa.Column('arrival_date', sa.DateTime(), nullable=False))
    op.drop_column('departure', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure', sa.Column('date', sa.DATETIME(), nullable=False))
    op.drop_column('departure', 'arrival_date')
    op.drop_column('departure', 'stopover_date')
    op.drop_column('departure', 'depart_date')
    # ### end Alembic commands ###
