"""empty message

Revision ID: c156a6acebc7
Revises: 15658559b591
Create Date: 2022-06-22 21:46:54.481926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c156a6acebc7'
down_revision = '15658559b591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'aircraft', ['plane'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
