"""empty message

Revision ID: c63a3cc45774
Revises: dddf20e3ed63
Create Date: 2022-06-17 00:42:53.644265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63a3cc45774'
down_revision = 'dddf20e3ed63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'aircraft', ['plane'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('airport', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
